use hal_core::module::Instruction;

#[cfg_attr(any(test, debug_assertions), derive(Debug))]
#[derive(Clone, PartialEq)]
pub enum WasmInstruction {
    AbsF32,
    AbsF64,

    AddF32,
    AddF64,
    AddI32,
    AddI64,

    AndI32,
    AndI64,

    Block(u32),
    BlockWithFuncType(u32, u32),
    BlockWithType(u32, u32),

    Br(u32),
    BrIf(u32),
    BrLabel(u32),
    BrTable(u32, u32),

    Call(u32),
    CallIndirect(u32, u32),

    CeilF32,
    CeilF64,

    CopysignF32,
    CopysignF64,

    ClzI32,
    ClzI64,

    ConstF32(f32),
    ConstF64(f64),
    ConstI32(i32),
    ConstI64(i64),

    CtzI32,
    CtzI64,

    DemoteF64F32,
    DivSI32,
    DivUI32,
    DivSI64,
    DivUI64,

    Drop128,
    Drop,
    Drop64,
    DropRef,

    Else(u32),
    End,
    EndBlockFrame,

    EqF32,
    EqF64,
    EqI32,
    EqI64,

    EqzI32,
    EqzI64,

    ExtendI32SI64,
    ExtendI32UI64,
    Extend16SI32,
    Extend16SI64,
    Extend32SI64,
    Extend8SI32,
    Extend8SI64,

    ExtendI32SF32,
    ExtendI32SF64,
    ExtendI32UF32,
    ExtendI32UF64,

    ExtendI64SF32,
    ExtendI64SF64,
    ExtendI64UF32,
    ExtendI64UF64,

    FloorF32,
    FloorF64,

    GeF32,
    GeF64,
    GeSI32,
    GeSI64,
    GeUI32,
    GeUI64,

    GlobalGet(u32),
    GlobalSet128(u32),
    GlobalSet32(u32),
    GlobalSet64(u32),
    GlobalSetRef(u32),

    GtF32,
    GtF64,
    GtSI32,
    GtSI64,
    GtUI32,
    GtUI64,

    Invoke(u32),

    LeF32,
    LeF64,
    LeSI32,
    LeSI64,
    LeUI32,
    LeUI64,

    LocalGet128(u32),
    LocalGet32(u32),
    LocalGet64(u32),
    LocalGetRef(u32),

    LocalSet128(u32),
    LocalSet32(u32),
    LocalSet64(u32),
    LocalSetRef(u32),

    LocalTee128(u32),
    LocalTee32(u32),
    LocalTee64(u32),
    LocalTeeRef(u32),

    Loop(u32),
    LoopWithFuncType(u32, u32),
    LoopWithType(u32, u32),

    LtF32,
    LtF64,
    LtSI32,
    LtSI64,
    LtUI32,
    LtUI64,

    MemoryCopy(u32, u32),
    MemoryFill(u32),
    MemoryGrow(u32),
    MemoryInit(u32, u32),
    MemorySize(u32),

    MulF32,
    MulF64,
    MulI32,
    MulI64,

    Nop,

    NeF32,
    NeF64,
    NeI32,
    NeI64,

    NegF32,
    NegF64,

    OrI32,
    OrI64,

    PopcntI32,
    PopcntI64,

    PromoteF32F64,

    RefFunc(u32),
    RefIsNull,
    RefNull(u32),

    ReinterpretF32I32,
    ReinterpretF64I64,
    ReinterpretI32F32,
    ReinterpretI64F64,

    RemSI32,
    RemSI64,
    RemUI32,
    RemUI64,

    Return,

    ReturnCall(u32),
    ReturnCallIndirect(u32, u32),

    RotlI32,
    RotlI64,
    RotrI32,
    RotrI64,

    Select128,
    Select32,
    Select64,
    SelectRef,

    ShlI32,
    ShlI64,

    ShrSI32,
    ShrSI64,
    ShrUI32,
    ShrUI64,

    SqrtF32,
    SqrtF64,

    StoreF32 { flags: u32, offset: u32 },
    StoreF64 { flags: u32, offset: u32 },
    StoreI32 { flags: u32, offset: u32 },
    StoreI64 { flags: u32, offset: u32 },
    Store16I32 { flags: u32, offset: u32 },
    Store16I64 { flags: u32, offset: u32 },
    Store32I64 { flags: u32, offset: u32 },
    Store8I32 { flags: u32, offset: u32 },
    Store8I64 { flags: u32, offset: u32 },

    SubF32,
    SubF64,
    SubI32,
    SubI64,

    TableCopy { from: u32, to: u32 },
    TableFill(u32),
    TableGet(u32),
    TableGrow(u32),
    TableInit(u32, u32),
    TableSet(u32),
    TableSize(u32),

    TruncF32SI32,
    TruncF32SI64,
    TruncF32UI32,
    TruncF32UI64,
    TruncF64SI32,
    TruncF64SI64,
    TruncF64UI32,
    TruncF64UI64,

    TruncSatF32SI32,
    TruncSatF32SI64,
    TruncSatF32UI32,
    TruncSatF32UI64,
    TruncSatF64SI32,
    TruncSatF64SI64,
    TruncSatF64UI32,
    TruncSatF64UI64,

    Unreachable,

    WrapI32I64,

    XorI32,
    XorI64,
}

impl From<WasmInstruction> for Instruction {
    fn from(wasm_inst: WasmInstruction) -> Self {
        match wasm_inst {
            WasmInstruction::AbsF32 => Instruction::AbsF32,
            WasmInstruction::AbsF64 => Instruction::AbsF64,
            WasmInstruction::AddF32 => Instruction::AddF32,
            WasmInstruction::AddF64 => Instruction::AddF64,
            WasmInstruction::AddI32 => Instruction::AddI32,
            WasmInstruction::AddI64 => Instruction::AddI64,
            WasmInstruction::AndI32 => Instruction::AndI32,
            WasmInstruction::AndI64 => Instruction::AndI64,
            WasmInstruction::Block(a) => Instruction::Block(a),
            WasmInstruction::BlockWithFuncType(a, b) => Instruction::BlockWithFuncType(a, b),
            WasmInstruction::BlockWithType(a, b) => Instruction::BlockWithType(a, b),
            WasmInstruction::Br(a) => Instruction::Br(a),
            WasmInstruction::BrIf(a) => Instruction::BrIf(a),
            WasmInstruction::BrLabel(a) => Instruction::BrLabel(a),
            WasmInstruction::BrTable(a, b) => Instruction::BrTable(a, b),
            WasmInstruction::Call(a) => Instruction::Call(a),
            WasmInstruction::CallIndirect(a, b) => Instruction::CallIndirect(a, b),
            WasmInstruction::CeilF32 => Instruction::CeilF32,
            WasmInstruction::CeilF64 => Instruction::CeilF64,
            WasmInstruction::ClzI32 => Instruction::ClzI32,
            WasmInstruction::ClzI64 => Instruction::ClzI64,
            WasmInstruction::ConstF32(a) => Instruction::ConstF32(a),
            WasmInstruction::ConstF64(a) => Instruction::ConstF64(a),
            WasmInstruction::ConstI32(a) => Instruction::ConstI32(a),
            WasmInstruction::ConstI64(a) => Instruction::ConstI64(a),
            WasmInstruction::CopysignF32 => Instruction::CopysignF32,
            WasmInstruction::CopysignF64 => Instruction::CopysignF64,
            WasmInstruction::CtzI32 => Instruction::CtzI32,
            WasmInstruction::CtzI64 => Instruction::CtzI64,
            WasmInstruction::DemoteF64F32 => Instruction::DemoteF64F32,
            WasmInstruction::DivSI32 => Instruction::DivSI32,
            WasmInstruction::DivUI32 => Instruction::DivUI32,
            WasmInstruction::DivSI64 => Instruction::DivSI64,
            WasmInstruction::DivUI64 => Instruction::DivUI64,
            WasmInstruction::Drop128 => Instruction::Drop128,
            WasmInstruction::Drop => Instruction::Drop32,
            WasmInstruction::Drop64 => Instruction::Drop64,
            WasmInstruction::DropRef => Instruction::DropRef,
            WasmInstruction::Else(a) => Instruction::Else(a),
            WasmInstruction::End => Instruction::End,
            WasmInstruction::EndBlockFrame => Instruction::EndBlockFrame,
            WasmInstruction::EqF32 => Instruction::EqF32,
            WasmInstruction::EqF64 => Instruction::EqF64,
            WasmInstruction::EqI32 => Instruction::EqI32,
            WasmInstruction::EqI64 => Instruction::EqI64,
            WasmInstruction::EqzI32 => Instruction::EqzI32,
            WasmInstruction::EqzI64 => Instruction::EqzI64,
            WasmInstruction::Extend16SI32 => Instruction::Extend16SI32,
            WasmInstruction::Extend16SI64 => Instruction::Extend16SI64,
            WasmInstruction::Extend32SI64 => Instruction::Extend32SI64,
            WasmInstruction::Extend8SI32 => Instruction::Extend8SI32,
            WasmInstruction::Extend8SI64 => Instruction::Extend8SI64,
            WasmInstruction::ExtendI32SF32 => Instruction::ExtendI32SF32,
            WasmInstruction::ExtendI32SF64 => Instruction::ExtendI32SF64,
            WasmInstruction::ExtendI32SI64 => Instruction::ExtendI32SI64,
            WasmInstruction::ExtendI32UI64 => Instruction::ExtendI32UI64,
            WasmInstruction::ExtendI32UF32 => Instruction::ExtendI32UF32,
            WasmInstruction::ExtendI32UF64 => Instruction::ExtendI32UF64,
            WasmInstruction::ExtendI64SF32 => Instruction::ExtendI64SF32,
            WasmInstruction::ExtendI64SF64 => Instruction::ExtendI64SF64,
            WasmInstruction::ExtendI64UF32 => Instruction::ExtendI64UF32,
            WasmInstruction::ExtendI64UF64 => Instruction::ExtendI64UF64,
            WasmInstruction::FloorF32 => Instruction::FloorF32,
            WasmInstruction::FloorF64 => Instruction::FloorF64,
            WasmInstruction::GeF32 => Instruction::GeF32,
            WasmInstruction::GeF64 => Instruction::GeF64,
            WasmInstruction::GeSI32 => Instruction::GeSI32,
            WasmInstruction::GeSI64 => Instruction::GeSI64,
            WasmInstruction::GeUI32 => Instruction::GeUI32,
            WasmInstruction::GeUI64 => Instruction::GeUI64,
            WasmInstruction::GlobalGet(a) => Instruction::GlobalGet(a),
            WasmInstruction::GlobalSet128(a) => Instruction::GlobalSet128(a),
            WasmInstruction::GlobalSet32(a) => Instruction::GlobalSet32(a),
            WasmInstruction::GlobalSet64(a) => Instruction::GlobalSet64(a),
            WasmInstruction::GlobalSetRef(a) => Instruction::GlobalSetRef(a),
            WasmInstruction::GtF32 => Instruction::GtF32,
            WasmInstruction::GtF64 => Instruction::GtF64,
            WasmInstruction::GtSI32 => Instruction::GtSI32,
            WasmInstruction::GtSI64 => Instruction::GtSI64,
            WasmInstruction::GtUI32 => Instruction::GtUI32,
            WasmInstruction::GtUI64 => Instruction::GtUI64,
            WasmInstruction::Invoke(a) => Instruction::Invoke(a),
            WasmInstruction::LeF32 => Instruction::LeF32,
            WasmInstruction::LeF64 => Instruction::LeF64,
            WasmInstruction::LeSI32 => Instruction::LeSI32,
            WasmInstruction::LeSI64 => Instruction::LeSI64,
            WasmInstruction::LeUI32 => Instruction::LeUI32,
            WasmInstruction::LeUI64 => Instruction::LeUI64,
            WasmInstruction::LocalGet128(a) => Instruction::LocalGet128(a),
            WasmInstruction::LocalGet32(a) => Instruction::LocalGet32(a),
            WasmInstruction::LocalGet64(a) => Instruction::LocalGet64(a),
            WasmInstruction::LocalGetRef(a) => Instruction::LocalGetRef(a),
            WasmInstruction::LocalSet128(a) => Instruction::LocalSet128(a),
            WasmInstruction::LocalSet32(a) => Instruction::LocalSet32(a),
            WasmInstruction::LocalSet64(a) => Instruction::LocalSet64(a),
            WasmInstruction::LocalSetRef(a) => Instruction::LocalSetRef(a),
            WasmInstruction::LocalTee128(a) => Instruction::LocalTee128(a),
            WasmInstruction::LocalTee32(a) => Instruction::LocalTee32(a),
            WasmInstruction::LocalTee64(a) => Instruction::LocalTee64(a),
            WasmInstruction::LocalTeeRef(a) => Instruction::LocalTeeRef(a),
            WasmInstruction::Loop(a) => Instruction::Loop(a),
            WasmInstruction::LoopWithFuncType(a, b) => Instruction::LoopWithFuncType(a, b),
            WasmInstruction::LoopWithType(a, b) => Instruction::LoopWithType(a, b),
            WasmInstruction::LtF32 => Instruction::LtF32,
            WasmInstruction::LtF64 => Instruction::LtF64,
            WasmInstruction::LtSI32 => Instruction::LtSI32,
            WasmInstruction::LtSI64 => Instruction::LtSI64,
            WasmInstruction::LtUI32 => Instruction::LtUI32,
            WasmInstruction::LtUI64 => Instruction::LtUI64,
            WasmInstruction::MemoryCopy(a, b) => Instruction::MemoryCopy(a, b),
            WasmInstruction::MemoryFill(a) => Instruction::MemoryFill(a),
            WasmInstruction::MemoryGrow(a) => Instruction::MemoryGrow(a),
            WasmInstruction::MemoryInit(a, b) => Instruction::MemoryInit(a, b),
            WasmInstruction::MemorySize(a) => Instruction::MemorySize(a),
            WasmInstruction::MulF32 => Instruction::MulF32,
            WasmInstruction::MulF64 => Instruction::MulF64,
            WasmInstruction::MulI32 => Instruction::MulI32,
            WasmInstruction::MulI64 => Instruction::MulI64,
            WasmInstruction::Nop => Instruction::Nop,
            WasmInstruction::NeF32 => Instruction::NeF32,
            WasmInstruction::NeF64 => Instruction::NeF64,
            WasmInstruction::NeI32 => Instruction::NeI32,
            WasmInstruction::NeI64 => Instruction::NeI64,
            WasmInstruction::NegF32 => Instruction::NegF32,
            WasmInstruction::NegF64 => Instruction::NegF64,
            WasmInstruction::OrI32 => Instruction::OrI32,
            WasmInstruction::OrI64 => Instruction::OrI64,
            WasmInstruction::PopcntI32 => Instruction::PopcntI32,
            WasmInstruction::PopcntI64 => Instruction::PopcntI64,
            WasmInstruction::PromoteF32F64 => Instruction::PromoteF32F64,
            WasmInstruction::RefFunc(a) => Instruction::RefFunc(a),
            WasmInstruction::RefIsNull => Instruction::RefIsNull,
            WasmInstruction::RefNull(a) => Instruction::RefNull(a),
            WasmInstruction::ReinterpretF32I32 => Instruction::ReinterpretF32I32,
            WasmInstruction::ReinterpretF64I64 => Instruction::ReinterpretF64I64,
            WasmInstruction::ReinterpretI32F32 => Instruction::ReinterpretI32F32,
            WasmInstruction::ReinterpretI64F64 => Instruction::ReinterpretI64F64,
            WasmInstruction::RemSI32 => Instruction::RemSI32,
            WasmInstruction::RemSI64 => Instruction::RemSI64,
            WasmInstruction::RemUI32 => Instruction::RemUI32,
            WasmInstruction::RemUI64 => Instruction::RemUI64,
            WasmInstruction::Return => Instruction::Return,
            WasmInstruction::ReturnCall(a) => Instruction::ReturnCall(a),
            WasmInstruction::ReturnCallIndirect(a, b) => Instruction::ReturnCallIndirect(a, b),
            WasmInstruction::RotlI32 => Instruction::RotlI32,
            WasmInstruction::RotlI64 => Instruction::RotlI64,
            WasmInstruction::RotrI32 => Instruction::RotrI32,
            WasmInstruction::RotrI64 => Instruction::RotrI64,
            WasmInstruction::Select128 => Instruction::Select128,
            WasmInstruction::Select32 => Instruction::Select32,
            WasmInstruction::Select64 => Instruction::Select64,
            WasmInstruction::SelectRef => Instruction::SelectRef,
            WasmInstruction::ShlI32 => Instruction::ShlI32,
            WasmInstruction::ShlI64 => Instruction::ShlI64,
            WasmInstruction::ShrSI32 => Instruction::ShrSI32,
            WasmInstruction::ShrSI64 => Instruction::ShrSI64,
            WasmInstruction::ShrUI32 => Instruction::ShrUI32,
            WasmInstruction::ShrUI64 => Instruction::ShrUI64,
            WasmInstruction::SqrtF32 => Instruction::SqrtF32,
            WasmInstruction::SqrtF64 => Instruction::SqrtF64,
            WasmInstruction::StoreF32 { flags, offset } => Instruction::StoreF32 { flags, offset },
            WasmInstruction::StoreF64 { flags, offset } => Instruction::StoreF64 { flags, offset },
            WasmInstruction::StoreI32 { flags, offset } => Instruction::StoreI32 { flags, offset },
            WasmInstruction::StoreI64 { flags, offset } => Instruction::StoreI64 { flags, offset },
            WasmInstruction::Store16I32 { flags, offset } => Instruction::Store16I32 { flags, offset },
            WasmInstruction::Store16I64 { flags, offset } => Instruction::Store16I64 { flags, offset },
            WasmInstruction::Store32I64 { flags, offset } => Instruction::Store32I64 { flags, offset },
            WasmInstruction::Store8I32 { flags, offset } => Instruction::Store8I32 { flags, offset },
            WasmInstruction::Store8I64 { flags, offset } => Instruction::Store8I64 { flags, offset },
            WasmInstruction::SubF32 => Instruction::SubF32,
            WasmInstruction::SubF64 => Instruction::SubF64,
            WasmInstruction::SubI32 => Instruction::SubI32,
            WasmInstruction::SubI64 => Instruction::SubI64,
            WasmInstruction::TableCopy { from, to } => Instruction::TableCopy { from, to },
            WasmInstruction::TableFill(a) => Instruction::TableFill(a),
            WasmInstruction::TableGet(a) => Instruction::TableGet(a),
            WasmInstruction::TableGrow(a) => Instruction::TableGrow(a),
            WasmInstruction::TableInit(a, b) => Instruction::TableInit(a, b),
            WasmInstruction::TableSet(a) => Instruction::TableSet(a),
            WasmInstruction::TableSize(a) => Instruction::TableSize(a),
            WasmInstruction::TruncF32SI32 => Instruction::TruncF32SI32,
            WasmInstruction::TruncF32SI64 => Instruction::TruncF32SI64,
            WasmInstruction::TruncF32UI32 => Instruction::TruncF32UI32,
            WasmInstruction::TruncF32UI64 => Instruction::TruncF32UI64,
            WasmInstruction::TruncF64SI32 => Instruction::TruncF64SI32,
            WasmInstruction::TruncF64SI64 => Instruction::TruncF64SI64,
            WasmInstruction::TruncF64UI32 => Instruction::TruncF64UI32,
            WasmInstruction::TruncF64UI64 => Instruction::TruncF64UI64,
            WasmInstruction::TruncSatF32SI32 => Instruction::TruncSatF32SI32,
            WasmInstruction::TruncSatF32SI64 => Instruction::TruncSatF32SI64,
            WasmInstruction::TruncSatF32UI32 => Instruction::TruncSatF32UI32,
            WasmInstruction::TruncSatF32UI64 => Instruction::TruncSatF32UI64,
            WasmInstruction::TruncSatF64SI32 => Instruction::TruncSatF64SI32,
            WasmInstruction::TruncSatF64SI64 => Instruction::TruncSatF64SI64,
            WasmInstruction::TruncSatF64UI32 => Instruction::TruncSatF64UI32,
            WasmInstruction::TruncSatF64UI64 => Instruction::TruncSatF64UI64,
            WasmInstruction::Unreachable => Instruction::Unreachable,
            WasmInstruction::WrapI32I64 => Instruction::WrapI32I64,
            WasmInstruction::XorI32 => Instruction::XorI32,
            WasmInstruction::XorI64 => Instruction::XorI64
        }
    }
}