[package]
name = "hal-wasm"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
hal-core = { path = "../core" }

[dev-dependencies]
hal-wat = { path = "../wat" }
